== The Flex client application
:icons: font
:rootdir: ../../../..
:srcdir: {rootdir}/client-flex/src

The client application is a simple Flex application which will receive object messages from a server messaging topic.
It's a single main MXML application which consists in 3 main parts:

. Bootstrap the GraniteDS container and configure the client components
. Define the Flex UI
. Define the callback for message reception

Here is the source code for the first bootstrap/configuration part:

[[client.destination]]
[source,xml,indent=0]
.main/flex/feed.mxml
----
include::{srcdir}/main/flex/feed.mxml[tags=client-setup]
----
<1> This bootstraps the GraniteDS Tide context in the application +preinitialize+ handler. Note that here we use the +Spring+
container integration but it can work with any server technology for most usual operations. However for real applications
with an EJB or CDI server it would be suitable to use the integration classes +Ejb+ and +Cdi+ which provide more specific support.
<2> We create a +Consumer+ component which is bound to the server topic named +feedTopic+ (see on the
<<server.destination,server application>> where this topic is defined) and configured with a subtopic named +NASDAQ+.
Note that we get the built-in +ServerSession+ component using +[Inject]+.
<3> We have to subscribe the +Consumer+ to its server topic.

The UI is a simple Flex mxml and has no dependency or specific requirement to work with GraniteDS. It is a simple panel
with a title and a tile group to which +StockPriceView+ components will be added when the first price values are received:

[source,xml,indent=0]
.main/flex/feed.mxml
----
include::{srcdir}/main/flex/feed.mxml[tags=client-ui]
----

The interesting part here is how to handle the incoming messages:

[source,actionscript,indent=0]
.main/flex/feed.mxml
----
include::{srcdir}/main/flex/feed.mxml[tags=client-consume]
----
<1> We have to register a +MessageEvent.MESSAGE+ listener, it will be called each time a message is received from the server
topic.
<2> The messages received by the listener contain an array of +StockPrice+ objects. The handler updates the UI
with the received data.

Note that the +StockPrice+ as3 class has been automatically generated by GDS from the Java class using the flexmojos maven plugin.
Here is how to use it in the module +pom.xml+:
[source,xml,indent=0]
.client-flex/pom.xml
----
<plugins>
    <plugin>
include::https://raw.github.com/graniteds-tutorials/graniteds-tutorial/master/client-flex/pom.xml[tags=maven-generate]
    ...
    </plugin>
</plugins>

include::{rootdir}/client-flex/pom.xml[tags=maven-gen-dep]
----

The generated AS3 contains a +String+ property +name+ and a +BigDecimal+ property +price+. The generator has been configured
to generate AS3 +BigDecimal+ instead of the default +Number+ using the extra option _externalizeBigDecimal_. We also have
to tell the server to serialize these values as +BigDecimal+ (see <<server.config,server configuration>>).

Finally here are the necessary maven dependencies and definitions to build the Flex module:
[source,xml,indent=0]
.client-flex/pom.xml
----
include::https://raw.github.com/graniteds-tutorials/graniteds-tutorial/master/client-flex/pom.xml[tags=maven-deps]

include::https://raw.github.com/graniteds-tutorials/graniteds-tutorial/master/client-flex/pom.xml[tags=maven-build-flex]
----
