/**
 * Generated by Gas3 v3.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.graniteds.tutorial.feed.entities {

    [Bindable]
    [RemoteClass(alias="org.graniteds.tutorial.feed.entities.StockPrice")]
    public class StockPrice extends StockPriceBase {

        public function StockPrice() {
            super();
        }
    }
}