/**
 * Generated by Gfx v3.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package org.graniteds.tutorial.feed.client;

import org.granite.client.messaging.RemoteAlias;
import org.granite.messaging.annotations.Serialized;

@Serialized
@RemoteAlias("org.graniteds.tutorial.feed.entities.StockPrice")
public class StockPrice extends StockPriceBase {

    private static final long serialVersionUID = 1L;
}